name: Generate Snake

on:
  push:
    branches:
      - main
      - master
  schedule:
    - cron: "0 0 * * *"  # Exécute tous les jours à minuit

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Generate Snake
        uses: Platane/snk@master
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: output/github-contribution-grid-snake.svg

      - name: Commit snake.svg
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add output/github-contribution-grid-snake.svg
          git commit -m "Update snake animation" || echo "No changes to commit"
          git push


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